### ISSUE TITLE
Please support Python3

### ISSUE THREAD

**Issue by tillea** [BD2KGenomics/bd2k-python-lib#17]
Hi,
bd2k is packaged for Debian.  Since Python2 will not be supported any more soon we would love to support Python3.  While it is possible to install the Python3 module it throws errors when using it.  Please switch to Python3 to be safe for the future.
Thank you, Andreas.

**Comment by DailyDreaming** [comment]
Not sure if this is very actively maintained.  If you're willing to contribute and make changes though, I'd be willing to review the code and merge in the necessary changes.

**Comment by mr-c** [comment]
Here's my attempt: https://github.com/BD2KGenomics/bd2k-python-lib/pull/19
